-- Seed data is intentionally empty.
--
-- Real product/listing imports should start from a clean database state.
-- Do not insert dummy products, variants, or platform listings here because
-- they pollute import validation and operator-facing listing audit views.
