-- Remote migration history alignment artifact.
--
-- Version 20260715000001 is already applied to the shared hosted Supabase
-- project (retailpulses_shared) and was authored outside this RPagentOS
-- migration ledger.
--
-- Source repository:  retailpulses/ticket-handling
-- Domain owner:       ticketing (DATABASE_OWNERSHIP.yaml)
--
-- This file intentionally contains no DDL and makes no ownership claim.
-- It exists solely to prevent the RPagentOS deployment workflow from
-- marking a valid remote migration as reverted or attempting to replay
-- another repository's schema change.
--
-- Reconciliation: retailpulses/RPagentOS#32
