-- Domain: order_management
-- Owner: retailpulses/OrderMgmt
-- Affected: shared hosted migration history only
-- Change class: additive
-- Hosted write required: no
-- Consumers: retailpulses/RPagentOS
-- History alignment for OrderMgmt migration 20260826014226_add_payment_method.sql. No executable SQL.
