-- Domain: inquiry
-- Owner: retailpulses/inquiry-automation
-- Affected: shared hosted migration history only
-- Change class: additive
-- Hosted write required: no
-- Consumers: retailpulses/RPagentOS
-- History alignment for inquiry-automation migration 20260904000400_prevent_backfill_needs_reply.sql. No executable SQL.
-- Cross-domain exception: https://github.com/retailpulses/RPagentOS/issues/105
