-- Domain: product_catalog
-- Owner: retailpulses/RPagentOS
-- Affected: catalog_sync_runs, catalog_sync_failures, catalog_change_outbox
-- Change class: additive
-- Hosted write required: yes
-- Consumers: retailpulses/CatalogSync, retailpulses/RPagentOS internal catalog API
--
-- RPagentOS#129 restores the owner-side operational schema that RPagentOS#32
-- adopted but which was absent from the canonical migration stream. The table
-- contract comes from CatalogSync's 003_catalogsync_operational_tables.sql at
-- commits 5da0263 and 0f23da5. RPagentOS#32 records the authoritative owner
-- corrections: variant references are UUID, client roles have no access, and a
-- legacy integer installation may be converted only when no non-null values
-- would be lost.
--
-- This migration sorts before 20260720020000, its first canonical dependent
-- migration. It is idempotent for both a clean database and hosted state.

CREATE TABLE IF NOT EXISTS public.catalog_sync_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    status text NOT NULL DEFAULT 'running',
    total_skus integer DEFAULT 0,
    upserted integer DEFAULT 0,
    skipped integer DEFAULT 0,
    not_found integer DEFAULT 0,
    catalog_unavailable integer DEFAULT 0,
    errors integer DEFAULT 0,
    presale_protected integer DEFAULT 0,
    mercari_triggered integer DEFAULT 0,
    price_changed integer DEFAULT 0,
    source_cursor text,
    duration_seconds numeric,
    error_summary text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.catalog_sync_failures (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id bigint REFERENCES public.catalog_sync_runs(id) ON DELETE SET NULL,
    item_code text NOT NULL,
    variant_id uuid REFERENCES public.product_variants(id) ON DELETE SET NULL,
    error_code text,
    error_message text,
    attempt_count integer NOT NULL DEFAULT 1,
    next_retry_at timestamptz,
    status text NOT NULL DEFAULT 'pending',
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_attempt_at timestamptz,
    resolved_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.catalog_change_outbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type text NOT NULL,
    item_code text NOT NULL,
    variant_id uuid REFERENCES public.product_variants(id) ON DELETE SET NULL,
    dedupe_key text,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'pending',
    available_at timestamptz NOT NULL DEFAULT now(),
    claimed_at timestamptz,
    claimed_by text,
    attempt_count integer NOT NULL DEFAULT 0,
    next_attempt_at timestamptz,
    last_error text,
    processed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- CREATE TABLE IF NOT EXISTS does not reconcile older installations.
ALTER TABLE public.catalog_sync_runs ADD COLUMN IF NOT EXISTS source_cursor text;
ALTER TABLE public.catalog_sync_runs ADD COLUMN IF NOT EXISTS duration_seconds numeric;
ALTER TABLE public.catalog_sync_runs ADD COLUMN IF NOT EXISTS error_summary text;
ALTER TABLE public.catalog_sync_failures ADD COLUMN IF NOT EXISTS run_id bigint REFERENCES public.catalog_sync_runs(id) ON DELETE SET NULL;
ALTER TABLE public.catalog_sync_failures ADD COLUMN IF NOT EXISTS variant_id uuid;
ALTER TABLE public.catalog_sync_failures ADD COLUMN IF NOT EXISTS error_code text;
ALTER TABLE public.catalog_sync_failures ADD COLUMN IF NOT EXISTS error_message text;
ALTER TABLE public.catalog_sync_failures ADD COLUMN IF NOT EXISTS attempt_count integer NOT NULL DEFAULT 1;
ALTER TABLE public.catalog_sync_failures ADD COLUMN IF NOT EXISTS next_retry_at timestamptz;
ALTER TABLE public.catalog_sync_failures ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'pending';
ALTER TABLE public.catalog_sync_failures ADD COLUMN IF NOT EXISTS first_seen_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.catalog_sync_failures ADD COLUMN IF NOT EXISTS last_attempt_at timestamptz;
ALTER TABLE public.catalog_sync_failures ADD COLUMN IF NOT EXISTS resolved_at timestamptz;
ALTER TABLE public.catalog_change_outbox ADD COLUMN IF NOT EXISTS variant_id uuid;

-- The pre-owner hosted tables used integer variant IDs. Fail closed if any
-- value would be discarded, otherwise perform the lossless type correction
-- recorded and tested in RPagentOS#32.
DO $block$
DECLARE
    target_table text;
    current_type text;
    populated bigint;
BEGIN
    FOREACH target_table IN ARRAY ARRAY['catalog_sync_failures', 'catalog_change_outbox']
    LOOP
        SELECT data_type
          INTO current_type
          FROM information_schema.columns
         WHERE table_schema = 'public'
           AND table_name = target_table
           AND column_name = 'variant_id';

        IF current_type IN ('integer', 'bigint', 'smallint') THEN
            EXECUTE format('SELECT count(*) FROM public.%I WHERE variant_id IS NOT NULL', target_table)
               INTO populated;
            IF populated <> 0 THEN
                RAISE EXCEPTION '% has % non-null legacy variant_id values; refusing lossy UUID conversion',
                    target_table, populated;
            END IF;
            EXECUTE format(
                'ALTER TABLE public.%I ALTER COLUMN variant_id TYPE uuid USING NULL::uuid',
                target_table
            );
        ELSIF current_type <> 'uuid' THEN
            RAISE EXCEPTION '%.variant_id has unsupported type %', target_table, current_type;
        END IF;
    END LOOP;
END
$block$;

DO $block$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conrelid = 'public.catalog_sync_failures'::regclass
           AND conname = 'catalog_sync_failures_variant_id_fkey'
    ) THEN
        ALTER TABLE public.catalog_sync_failures
            ADD CONSTRAINT catalog_sync_failures_variant_id_fkey
            FOREIGN KEY (variant_id) REFERENCES public.product_variants(id) ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conrelid = 'public.catalog_change_outbox'::regclass
           AND conname = 'catalog_change_outbox_variant_id_fkey'
    ) THEN
        ALTER TABLE public.catalog_change_outbox
            ADD CONSTRAINT catalog_change_outbox_variant_id_fkey
            FOREIGN KEY (variant_id) REFERENCES public.product_variants(id) ON DELETE SET NULL;
    END IF;
END
$block$;

CREATE INDEX IF NOT EXISTS catalog_sync_runs_started_at_idx
    ON public.catalog_sync_runs (started_at DESC);
CREATE INDEX IF NOT EXISTS catalog_sync_failures_open_retry_idx
    ON public.catalog_sync_failures (status, next_retry_at) WHERE resolved_at IS NULL;
CREATE INDEX IF NOT EXISTS catalog_sync_failures_item_code_idx
    ON public.catalog_sync_failures (item_code, id DESC);
CREATE UNIQUE INDEX IF NOT EXISTS catalog_sync_failures_one_open_per_sku_uidx
    ON public.catalog_sync_failures (item_code) WHERE resolved_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS catalog_change_outbox_dedupe_uidx
    ON public.catalog_change_outbox (dedupe_key) WHERE dedupe_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS catalog_change_outbox_claim_idx
    ON public.catalog_change_outbox (status, available_at, next_attempt_at);

ALTER TABLE public.catalog_sync_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalog_sync_failures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalog_change_outbox ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.catalog_sync_runs, public.catalog_sync_failures,
    public.catalog_change_outbox FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.catalog_sync_runs, public.catalog_sync_failures,
    public.catalog_change_outbox TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

-- Forward recovery: fix the authoritative source or unexpected hosted type,
-- then rerun this migration. Rollback: drop only newly created empty tables;
-- do not drop adopted hosted tables or rewrite their historical rows.
