-- Domain: inquiry
-- Owner: retailpulses/inquiry-automation
-- Affected: shared hosted migration history only
-- Change class: additive
-- Hosted write required: no
-- Consumers: retailpulses/RPagentOS
-- History alignment for inquiry-automation migration 20260904000100_canary_latest_api_inquiry_product_link.sql. No executable SQL.
