-- Domain: order_management
-- Owner: retailpulses/OrderMgmt
-- Affected: shared hosted migration history only
-- Change class: additive
-- Hosted write required: no
-- Consumers: retailpulses/RPagentOS
-- History alignment for OrderMgmt migration 20260830021246_add_rakuten_status_audit.sql. No executable SQL.
